#!/usr/bin/env python3
"""
PRIME-X Configuration Generator
================================
Reads config/config.json and generates platform-specific config files:
- core/include/prime_config.h (C++)
- bridge/config.go (Go)
"""

import json
import os
import sys

# ============================================================
#  LOAD CONFIG
# ============================================================
try:
    with open('config/config.json', 'r') as f:
        config = json.load(f)
except FileNotFoundError:
    print("ERROR: config/config.json not found! Must be in project root/config.")
    sys.exit(1)

# ============================================================
#  EXTRACT VALUES
# ============================================================
bits = config['system']['prime_bits']
raw_size = config['system']['raw_size_bytes']

# VALIDATION: RAW_SIZE must match BITS
import math
expected_raw_size = math.ceil(bits / 8)
if raw_size != expected_raw_size:
    print(f"ERROR: prime_bits={bits} requires raw_size_bytes={expected_raw_size}, but found {raw_size}")
    print(f"       Fix config.json: set raw_size_bytes={expected_raw_size}")
    sys.exit(1)

# VALIDATION: model.input_dimension should match prime_bits for consistency
model_input_dim = config['model']['input_dimension']
if model_input_dim != bits:
    print(f"WARNING: model.input_dimension ({model_input_dim}) != prime_bits ({bits})")
    print(f"         This mismatch will cause ML to fail!")
    print(f"         Consider updating config.json: model.input_dimension = {bits}")
    # Note: We continue anyway - the ML pipeline validation will catch this

# Network
zmq_host = config['network']['zmq_host']
zmq_port_core_push = config['network']['zmq_port_core_push']
zmq_port_core_pub = config['network']['zmq_port_core_pub']
grpc_host = config['network']['grpc_host']
grpc_port = config['network']['grpc_port']

# Crypto
noise_sigma = config['crypto']['noise_sigma']
miller_rabin_rounds = config['crypto']['miller_rabin_rounds']
chacha20_key_size = config['crypto']['chacha20_key_size']

# Buffer
cpp_internal_queue_max = config['buffer']['cpp_internal_queue_max']
go_buffer_size = config['buffer']['go_channel_buffer_size']

# Packet structure (calculated dynamically from config) - v1 WITH INTEGRITY TRAILER
# BASE: [type:4][raw:RAW_SIZE][floats:BITS*4]
# TRAILER: [magic:4][version:1][reserved:3][seq:8][raw_hash:32][vec_hash:32][all_hash:32] = 112 bytes
# Total packet size = 4 + RAW_SIZE + (BITS * 4) + 112
type_header_size = 4  # int32 type field
float_vector_size = bits * 4  # BITS * 4 bytes (float32 per bit)
trailer_size = 112  # magic(4) + version(1) + reserved(3) + seq(8) + 3×hash(96) = 112
packet_size = type_header_size + raw_size + float_vector_size + trailer_size  # 4 + RAW_SIZE + (BITS*4) + 112

print(f">>> [PRIME-X CONFIGURATOR] System: {bits}-bit | Packet Size: {packet_size} bytes")
print(f"    Packet Structure (v1 integrity trailer):")
print(f"      BASE: [type:4] + [raw:{raw_size}] + [floats:{float_vector_size}]")
print(f"      TRAILER: [magic:4|version:1|reserved:3|seq:8|hashes:96] = 112 bytes")
print(f"    Network: {zmq_host}:{zmq_port_core_push} (ZMQ Push)")
print(f"    gRPC: {grpc_host}:{grpc_port}")
print(f"    Crypto: noise_sigma={noise_sigma}, mr_rounds={miller_rabin_rounds}")
# ============================================================
#  A. C++ HEADER GENERATION (core/include/prime_config.h)
# ============================================================
cpp_content = f"""#ifndef PRIME_CONFIG_H
#define PRIME_CONFIG_H

#include <string>

namespace Config {{
    // System Parameters (GENERATED FROM config/config.json)
    const int BITS = {bits};
    const int RAW_SIZE = {raw_size};
    const int PACKET_SIZE = {packet_size};  // [type:4][raw:{raw_size}][floats:{float_vector_size}][trailer:112]
    
    // Network Configuration
    const std::string ZMQ_HOST = "{zmq_host}";
    const int ZMQ_PORT_CORE_PUSH = {zmq_port_core_push};  // C++ binds PUSH here
    const int ZMQ_PORT_CORE_PUB = {zmq_port_core_pub};    // C++ binds PUB here (for commands)
    
    // Cryptographic Parameters
    const float NOISE_SIGMA = {noise_sigma}f;
    const int MILLER_RABIN_ROUNDS = {miller_rabin_rounds};
    const int CHACHA20_KEY_SIZE = {chacha20_key_size};
    const int BLAKE2S_OUTPUT_BITS = 256;
    
    // Buffer Configuration
    const size_t INTERNAL_QUEUE_MAX = {cpp_internal_queue_max};
}}

#endif // PRIME_CONFIG_H
"""

os.makedirs('core/include', exist_ok=True)
with open('core/include/prime_config.h', 'w') as f:
    f.write(cpp_content)
print(f"  ✓ C++ Header Generated: core/include/prime_config.h")

# ============================================================
#  B. GO CONFIG GENERATION (bridge/config.go)
# ============================================================
go_content = f"""package main

// AUTO-GENERATED by configure.py
// DO NOT EDIT — modify config/config.json instead

const (
    // System Parameters
    BITS             = {bits}
    DEFAULT_RAW_SIZE = {raw_size}
    DEFAULT_BITS     = {bits}
    PACKET_SIZE      = {packet_size}  // [type:4][raw:{raw_size}][floats:{float_vector_size}]
    
    // Network Configuration
    ZMQ_CORE_PULL    = "tcp://{zmq_host}:{zmq_port_core_push}"  // Connect to C++ PUSH
    ZMQ_CORE_PUB     = "tcp://*:{zmq_port_core_pub}"            // SUB commands from C++
    GRPC_HOST        = "{grpc_host}"
    GRPC_PORT        = ":{grpc_port}"
    
    // Cryptographic Parameters
    NOISE_SIGMA              = {noise_sigma}
    MILLER_RABIN_ROUNDS      = {miller_rabin_rounds}
    CHACHA20_KEY_SIZE        = {chacha20_key_size}
    BLAKE2S_OUTPUT_BITS      = 256
    
    // Buffer Configuration
    BUFFER_SIZE     = {go_buffer_size}  // Go channel buffer
)
"""

os.makedirs('bridge', exist_ok=True)
with open('bridge/config.go', 'w') as f:
    f.write(go_content)
print(f"  ✓ Go Config Generated: bridge/config.go")

print("\n✓ Configuration generation complete!")